# Generated by Django 4.0.5 on 2022-08-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barmas', '0003_alter_bmasuk_k_ikan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmasuk',
            name='j_ikan',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bmasuk',
            name='k_ikan',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bmasuk',
            name='ket',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='bmasuk',
            name='m_kend',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bmasuk',
            name='p_kend',
            field=models.CharField(default='', max_length=10),
        ),
    ]
