# Generated by Django 4.0.5 on 2022-08-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenisikan', '0002_alter_jenisikan_g_ikan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisikan',
            name='j_ikan',
            field=models.CharField(default='', max_length=30),
        ),
    ]
